{% set name = "httpx-ws" %}
{% set version = "0.5.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/httpx_ws-{{ version }}.tar.gz
  sha256: 327537b7079ae32cf8bcc7b1285b795233393495e4d13ce5ed116b4f1a03273d

build:
  number: 0
  script: {{ PYTHON }} -m pip install . -vv
  noarch: python

requirements:
  host:
    - python >=3.8
    - hatchling
    - hatch-regex-commit
    - pip
  run:
    - python >=3.8
    - anyio
    - httpx >=0.23.1
    - httpcore >=0.17.3
    - wsproto

test:
  imports:
    - httpx_ws
  requires:
    - pip
  commands:
    - pip check

about:
  home: https://github.com/frankie567/httpx-ws
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: WebSocket support for HTTPX
  doc_url: https://frankie567.github.io/httpx-ws
  dev_url: https://github.com/frankie567/httpx-ws

extra:
  recipe-maintainers:
    - davidbrochart
    - frankie567
