{% set name = "httpx-ws" %}
{% set version = "0.3.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/httpx_ws-{{ version }}.tar.gz
  sha256: 694cf6d52622167cfc611c854312039dad03e470abbaf2efcfdbb08a3c29f1eb

build:
  number: 0
  script: {{ PYTHON }} -m pip install . -vv
  noarch: python

requirements:
  host:
    - python >=3.7
    - hatchling
    - hatch-regex-commit
    - pip
  run:
    - python >=3.7
    - anyio
    - httpx >=0.23.1
    - httpcore >=0.16.1
    - wsproto
    - typing-extensions

test:
  imports:
    - httpx_ws
  requires:
    - pip
  commands:
    - pip check

about:
  home: https://github.com/frankie567/httpx-ws
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: WebSocket support for HTTPX
  doc_url: https://frankie567.github.io/httpx-ws
  dev_url: https://github.com/frankie567/httpx-ws

extra:
  recipe-maintainers:
    - davidbrochart
    - frankie567
