{% set name = "httpx-ws" %}
{% set version = "0.6.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/httpx_ws-{{ version }}.tar.gz
  sha256: b07446b9067a30f1012fa9851fdfd14207012cd657c485565884f90553d0854c

build:
  number: 0
  script: {{ PYTHON }} -m pip install . -vv
  noarch: python

requirements:
  host:
    - python >=3.8
    - hatchling
    - hatch-regex-commit
    - pip
  run:
    - python >=3.8
    - anyio >=4
    - httpx >=0.23.1
    - httpcore >=1.0.4
    - wsproto

test:
  imports:
    - httpx_ws
  requires:
    - pip
  commands:
    - pip check

about:
  home: https://github.com/frankie567/httpx-ws
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: WebSocket support for HTTPX
  doc_url: https://frankie567.github.io/httpx-ws
  dev_url: https://github.com/frankie567/httpx-ws

extra:
  recipe-maintainers:
    - davidbrochart
    - frankie567
